# Generated by Django 5.0.6 on 2024-06-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'verbose_name': 'Стол', 'verbose_name_plural': 'Столы'},
        ),
        migrations.AddField(
            model_name='order',
            name='count',
            field=models.IntegerField(default=1, verbose_name='Количество'),
            preserve_default=False,
        ),
    ]
