# Generated by Django 5.0.6 on 2024-06-20 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_order_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated_at',
        ),
    ]
